### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by lolek12** [Sasuke78200/GTAV_CustomScriptLoader#1]
Hey man, 
I was wondering if you could provide some commenting on all the files in this project or some sort of source where I could read more about loading scripts without then need to compress or encrypt data?
Keep it up!

Peace

**Comment by Sasuke78200** [comment]
Yeah i'll do it, on the next commit.

**Comment by lolek12** [comment]
Thanks G!

**Comment by lolek12** [comment]
Sasuke, could you direct me somewhere I could learn more about this? Thanks for the comments!

**Comment by Sasuke78200** [comment]
Wow, I can't say if there's a documentation about this somewhere.
All of this is from my personnal researches.

**Comment by lolek12** [comment]
Thanks, sorry for bothering so much. I assume this script wont let us load the .ysc files from Rockstar, right?

**Comment by Sasuke78200** [comment]
No problem bro', it will allow us to load script from Rockstar too, but you'll need to decrypt/decompress them first.

**Comment by lolek12** [comment]
Oh yea.. That makes sense, so Blades files would run no problem. That will definitely help discovering some new NATIVES. You reckon it'll ever be possible to decompile these scripts to its source state?

**Comment by Sasuke78200** [comment]
We will never be able to decompile the scripts to "its source state", we can only make them readable with known language (like C or others). But we don't know what R*'s scripting language looks like :/
